spring:
  datasource:
    password: MicroService_p4$$
    username:  microservice_user
    url: 'jdbc:mysql://35.237.112.170:3306/microservice_transportador_db'
  jpa:
    hibernate:
      ddl-auto: update
