spring:
  datasource:
    password: !$&H0m3369
    username: root
    url: 'jdbc:mysql://localhost:3306/microservice_db'
    #url: 'jdbc:mysql://35.237.112.170:3306/microservice_db'
  jpa:
    hibernate:
      ddl-auto: update
  #Configurações para resolver Hystrix caindo no fallback em toda requisição.
  hikari:
    connection-test-query: SELECT 1 FROM DUAL
    minimum-idle: 2
    maximum-pool-size: 6
    pool-name: havasPoolName
    auto-commit: false
    type: com.zaxxer.hikari.HikariDataSource
    connection-timeout: 3000      
    idle-timeout: 40000
    max-lifetime: 900000
      
#security:
#  oauth2:
#  resource:
#     user-info-uri: https://auth-cadalso.herokuapp.com/user #A URL do servidor de autenticação que retorna os dados do usuário autenticado.         
