spring:
  datasource:
    password: MicroService_p4$$
    username:  microservice_user
    url: 'jdbc:mysql://35.237.112.170:3306/microservice_db'
  jpa:
    hibernate:
      ddl-auto: update
  #Configurações para resolver Hystrix caindo no fallback em toda requisição.
  hikari:
    connection-test-query: SELECT 1 FROM DUAL
    minimum-idle: 1
    maximum-pool-size: 5
    pool-name: havasPoolName
    auto-commit: false
    type: com.zaxxer.hikari.HikariDataSource
      
#security:
#  oauth2:
#  resource:
#     user-info-uri: https://auth-cadalso.herokuapp.com/user #A URL do servidor de autenticação que retorna os dados do usuário autenticado.         
