spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: '!$&H0m3369'
    username: root
    url: 'jdbc:mysql://localhost:3306/microservice_db'
    #url: 'jdbc:mysql://35.237.112.170:3306/microservice_db'    

